language: objective-c

matrix:
  include:
    - osx_image: xcode7.3
      env: TEST_ONLY="NO" SIM="iphonesimulator9.3"
    - osx_image: beta-xcode6.1
      env: TEST_ONLY="YES" SIM="iphonesimulator7.0"

script:
  - COMMAND="xctool -project TravisMultiOsTest/TravisMultiOsTest.xcodeproj -scheme TravisMultiOsTest -sdk '$SIM' test"
  - if [ $TEST_ONLY == "NO" ]; then
      COMMAND+=" build";
    fi
  - eval $COMMAND  
